services:
  - type: web
    name: ytbseo-suite
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app.core.wsgi:application --log-file -
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: "False"
      - key: YOUTUBE_API_KEY
        sync: false
      - key: GOOGLE_API_KEY
        sync: false
